version: '3.8'

services:
  # Redis для хранения сигнатур
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - waf-net

  # Сервис для управления сигнатурами
  signaturedb:
    build:
      context: ./signaturedb
    ports:
      - "8082:8082"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    networks:
      - waf-net

  # Анализатор запросов
  analyzer:
    build:
      context: ./analyzer
    ports:
      - "8083:8083"
    networks:
      - waf-net

  # Сам WAF Proxy
  wafproxy:
    build:
      context: ./wafproxy
    ports:
      - "8081:8081" # Внешний порт для доступа к WAF
    environment:
      - TARGET_URL=http://192.168.200.50:7000
      - REDIS_ADDR=redis:6379
      - ANALYZER_URL=http://analyzer:8083/analyze
    depends_on:
      - redis
      - analyzer
    networks:
      - waf-net

networks:
  waf-net:

volumes:
  redis_data: